include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Treat info-level lints as warnings (or ignore)
    # use_build_context_synchronously: ignore
    # prefer_final_fields: ignore
    # unnecessary_import: ignore
    # depend_on_referenced_packages: ignore
    # unnecessary_to_list_in_spreads: ignore
    library_private_types_in_public_api: ignore
    # no_leading_underscores_for_local_identifiers: ignore

    # Unused code
    # unused_import: ignore
    # unused_field: ignore
    # unused_element: ignore
    # unused_local_variable: ignore

linter:
  rules:
    # Disable strict clean-code rules (for large UI apps)
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_final_fields: false
    avoid_print: false

    # Async context warnings
    use_build_context_synchronously: false

    # Naming & visibility
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false

    # Imports
    depend_on_referenced_packages: false

    # Collections
    unnecessary_to_list_in_spreads: false
